### ISSUE TITLE
[Meta] Cache the rendered addon to improve perceived performance

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1090]
[edit @k88hudson]

- [x] Change vendor strategy to allow dependencies to be used in common #1256
- [x] Refactor redux store to be used on addon and content side #1257
- [x] Add page worker to cache and allow rehydration of redux state #1258 
- [ ] Add html caching via rendering to a string and storing in locastorage (needs bug)

We should find a way to pre render the display content of the new tab page and then quickly access that from a cache so that when someone starts a new tab we don't go through the entire render/query flow each time.

**Comment by rlr** [comment]
see also issue #320

**Comment by jaredkerim** [comment]
Close attention needs to be paid to how this affects UX and data staleness.

**Comment by jaredkerim** [comment]
This will be handled in #1092

**Comment by jaredkerim** [comment]
Reopening and assigning to @k88hudson with the design using page workers:

https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-worker

to asynchronously render the page in page worker and store the output in a way that can quickly be sent to new tabs.
