### ISSUE TITLE
Better Top Sites

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#1311]
Heretofore known as Top Sites v2. Top Sites is the most popular feature on new tab, but we all know there are a [number](https://github.com/mozilla/activity-stream/issues/1300) [of](https://github.com/mozilla/activity-stream/issues/603) [issues](https://github.com/mozilla/activity-stream/issues/405), and it could be much improved. 

Below are some key changes I suggest we make to improve Top Sites.
## Improve the most popular icons

We are still missing distinctive icons from some very popular sites (mostly Google properties). We also have many icons that are poor quality.

We should:
- [x] [Use larger icons when available (`apple-touch-icons`)](https://github.com/mozilla/activity-stream/issues/1383) (Fixed in [**page-metadata-parser**](https://github.com/mozilla/page-metadata-parser/blob/18c334a9b7cc613e52f5e7ef3138e7294747b7ea/parser.js#L58-L59))
- [x] [Add missing popular sites to Tippy Top](https://github.com/mozilla/activity-stream/issues/1384) (Possibly https://github.com/nchapman/tippy-top-sites/issues/37?)
- [x] [Provide distinct icons for popular properties like Google](https://github.com/mozilla/activity-stream/issues/1385) (See https://github.com/nchapman/tippy-top-sites/issues/42)
- [ ] [Allow multiple URL patterns for Tippy Top entries](https://github.com/mozilla/activity-stream/issues/1386) to cover cases like `gmail.com` + `mail.google.com` (See https://github.com/nchapman/tippy-top-sites/issues/41)
## Reduce duplication

We are showing duplicates in Top Sites. Sometimes these are actual duplicates with slightly different URLs (`http` vs `https`, `www` vs `nowww`, etc). Sometimes these are due to redirects (`gmail.com` to `mail.google.com`). Other times they are actually different sites (pages), but they look the same. We **shouldn't** consider this last category to be duplicates, but instead should improve their differentiation (covered next).

We should:
- [x] [Collapse very similar URLs and combine their frecency](https://github.com/mozilla/activity-stream/issues/1387)
- [ ] [Collapse redirected URLs and combine their frecency](https://github.com/mozilla/activity-stream/issues/1388)*
- [ ] Sort them by the combined frecency

*_Detecting redirects might be a challenge. Ideally we'd keep the site that's the destination of the redirect instead of continuing to encourage that redirect pattern._
## Improve differentiation

Top Sites is somewhat misleadingly named. It's actually Top Pages, but people seem to understand the Top Sites label so let's not worry too much about that for now.

You can imagine multiple examples of different pages from the same site appearing to look the same. The common example is `reddit.com`, `reddit.com/r/funny`, `reddit.com/r/movies`. In Top Sites these all say `reddit.com`, and you can't tell the difference.

We should provide the most specific label that we can for these items (even if you don't have confusing repeats). The unfortunate reality is that we very often don't have the page title (might be due to redirects?), so we'll have to do our best with the URL.
### Better labels from URLs

For top level domains, we should use the most meaningful part of the domain (try to drop the `.com`/`.net`/`.co.uk`). For URLs that include a path we should use the last section of the path. This will sometimes lead to poor results but should work reasonably well most of the time. Here are my most frecent pages for examples. Unfortunately I don't have any reddit Top Sites so just use your imagination :smile:.

| URL | Type | Action | Label | :confused: |
| --- | --- | --- | --- | --- |
| https://news.ycombinator.com/ | TLD | Keep | news.ycombinator |  |
| https://sql.telemetry.mozilla.org/ | TLD | Keep | sql.telemetry.mozilla |  |
| http://sso.mozilla.com/ | TLD | Keep | sso.mozilla |  |
| http://news.ycombinator.com/ | TLD | Keep | news.ycombinator |  |
| http://youtube.com/ | TLD | Keep | youtube |  |
| https://sso.mozilla.com/ | TLD | Combine |  |  |
| https://addons.mozilla.org/en-US/firefox/ | Path | Keep | firefox | :cry: |
| https://addons.mozilla.org/ | TLD | Combine |  |  |
| http://images.google.com/ | TLD | Keep | images.google |  |
| http://digg.com/ | TLD | Keep | digg |  |
| https://images.google.com/?gws_rd=ssl | TLD | Combine |  |  |
| http://www.macrumors.com/ | TLD | Keep | macrumors |  |
| http://www.apple.com/ | TLD | Keep | apple |  |
| http://smile.amazon.com/ | TLD | Keep | smile.amazon |  |
| https://trello.com/b/KX3hV8XS/activity-stream | Path | Keep | activity-stream |  |
| https://smile.amazon.com/ | TLD | Combine |  |  |
| http://daringfireball.net/ | TLD | Keep | daringfireball |  |
| http://localhost:5000/ | TLD | Keep | localhost |  |
| https://phonebook.mozilla.org/mellon/login?ReturnTo=https... | Path | Keep | login | :cry: |

We should:
- [x] [Show shorter labels for top level URLs](https://github.com/mozilla/activity-stream/issues/1376)
- [ ] Show more specific labels for URLs with paths
## That's all for now

These changes should address the most common (egregious) problems that we have in Top Sites. It will also put us in a good place to try some new ideas in the future like time of day weighting or multiple rows of Top Sites.

Let me know what you think or where I've got it wrong!

**Comment by pdehaan** [comment]
I don't understand what your "Keep" vs "Combine" column means in your fancy table above, but I appreciate your emoji game.

The one bigger problem is that you're now relying on something like https://trello.com/b/KX3hV8XS/activity-stream. If that URL parts were somewhat inverted, you'd have a "pretty bad experience". For example, https://trello.com/b/activity-stream/KX3hV8XS would then show you a label of "KX3hV8XS" and you'd get no value (whereas a domain is probably more predictable).

I think one of my main problems (apart from it being technically "Top Pages", not sites), is that we don't have enough space to play around.
I can hack the DOM locally, and your "sql.telemetry.mozilla" gets truncated to "sql.telemetry....", so I don't even see the _actual_ domain.

Not sure if I can sell you on an `og:site_name` solution, since it would rely on some optional open graph tags on sites: http://ogp.me/#optional

I don't see a bug for that in [**mozilla/page-metadata-parser**](https://github.com/mozilla/page-metadata-parser/issues), so I guess I'll start by kvetching over there.

But in the case of http://www.espn.com/nba/, it'd give me:
```html
<meta property="og:site_name" content="ESPN.com">
```

Or in the case of http://www.imdb.com/title/tt0060666/?ref_=nv_sr_1, it'd give me:
```html
<meta property='og:site_name' content='IMDb' />
```

Not entirely consistent, but it's what the page creator/author wanted (because they set it in Open Graph meta).

**Comment by pdehaan** [comment]
Also, i've really struggled w/ redirects. Like, if I try going to outlook.com, it redirects me to https://login.live.com/login.srf?wa=wsignin1.0&ct=1473983384&rver=6.6.6556.0&wp=MBI_SSL&wreply=https:%2F%2Foutlook.live.com%2Fowa%2F&id=292841&CBCXT=out. So i'd definitely never want to see any of that, and I'd prefer my original bookmark/history.

**Comment by pdehaan** [comment]
> Re: _"Use larger icons when available (`apple-touch-icons`)"_

FWIW, this should be _much_ better when we switch over to using our [metadata service proxy](https://github.com/mozilla/page-metadata-service), per the rules in [**mozilla/page-metadata-parser** /parser.js:56-69](
https://github.com/mozilla/page-metadata-parser/blob/18c334a9b7cc613e52f5e7ef3138e7294747b7ea/parser.js#L56-L69):

```js
  icon_url: {
    rules: [
      ['link[rel="apple-touch-icon"]', node => node.element.getAttribute('href')],
      ['link[rel="apple-touch-icon-precomposed"]', node => node.element.getAttribute('href')],
      ['link[rel="icon"]', node => node.element.getAttribute('href')],
      ['link[rel="fluid-icon"]', node => node.element.getAttribute('href')],
      ['link[rel="shortcut icon"]', node => node.element.getAttribute('href')],
      ['link[rel="Shortcut Icon"]', node => node.element.getAttribute('href')],
      ['link[rel="mask-icon"]', node => node.element.getAttribute('href')],
    ],
    processors: [
      (icon_url, context) => makeUrlAbsolute(context.url, icon_url)
    ]
  },
```

**Comment by pdehaan** [comment]
> pdehaan says: _"Not sure if I can sell you on an `og:site_name` solution"_

@nchapman Correctly pointed out that this doesn't always play nice because technically:

> `og:site_name` - If your object is part of a larger web site, the name which should be displayed for the **overall site**. e.g., "IMDb".
>
> &mdash; via http://ogp.me/#optional

So each subreddit page would potentially just have `<meta property="og:site_name" content="reddit">` and all our Reddit themed Top Sites would look the same.

**Comment by pdehaan** [comment]
Not sure how you're getting your frecent browsing history, but here's my #/debug page History:

![new_tab](https://cloud.githubusercontent.com/assets/557895/18571406/0516cc02-7b67-11e6-9e05-0a0aeafc32ec.png)

| URL | Type | Action   | Label | :confused: |
|----|----|----|----|----|
| https://github.com/mozilla-services/pageshot/search?q=XPI | Path | Keep | search | :poop:
| https://github.com/mozilla/blok/pull/148 | Path | Keep | 148 | :poop:
| http://testpilot.dev.mozaws.net/experiments/blok | Path | Keep | blok | :poop:
| https://github.com/mozilla/blok/pulls | Path | Keep | pulls | :poop:
| https://github.com/mozilla/blok/projects | Path | Keep | projects | :poop:
| https://github.com/mozilla/blok/blob/44f47c4b4fc6633657e7bc0755e8c640b4c51841/web-ext-artifacts/blok-1.0rc7.xpi | Path | Keep | blok-1.0rc7.xpi❓  | :poop:
| https://www.reddit.com/r/gaming | Path | Keep | gaming | ❔ 
| http://testpilot.dev.mozaws.net/experiments | Path | Keep | experiments | ❔ 
| http://testpilot.dev.mozaws.net/ | TLD | Keep | testpilot.dev.mozaws❓ | - 
| https://pageshot.dev.mozaws.net/?pageshot-not-installed | TLD | Keep | pageshot.dev.mozaws❓ | -
| https://pageshot.dev.mozaws.net/__version__ | Path | Keep | \_\_version\_\_ | :poop:
| https://pageshot.dev.mozaws.net/ | TLD | Keep | pageshot.dev.mozaws❓ | -
| https://pageshot.dev.mozaws.net/leave-page-shot | Path | Keep | leave-page-shot❓ | -
| https://pageshot.dev.mozaws.net/terms | Path | Keep | terms❓ | -
| https://pageshot.dev.mozaws.net/homepage/install-test-local.html | Path | Keep | install-test-local.html❓ | :poop:
| https://pageshot.net/ | TLD | Keep | pageshot | -
| https://raw.githubusercontent.com/mozilla/blok/44f47c4b4fc6633657e7bc0755e8c640b4c51841/web-ext-artifacts/blok-1.0rc7.xpi | Path | Keep | blok-1.0rc7.xpi❓ | :poop:
| https://pageshot.dev.mozaws.net/homepage/install.html | Path | Keep | install.html❓ | :poop:

**Comment by nchapman** [comment]
> Not sure how you're getting your frecent browsing history, but here's my #/debug page History:

I don't think this approach will work as well on general history, but it might work well enough on frecent pages.

I queried my places.sqlite db directly with:

`select url, frecency from moz_places order by frecency DESC limit 100;`

**Comment by pdehaan** [comment]
Another fun fact that I just remembered... Currently, if I take a page shot in Page Shot, I get a snazzy URL like https://pageshot.dev.mozaws.net/0jwCSt1vR3lvgFnd/www.bing.com

![bing](https://cloud.githubusercontent.com/assets/557895/18603544/4e871318-7c27-11e6-93fc-a1c1d0619036.png)

You'll possibly notice that the URL is pageshot.net/{stuff}/{domain}, so by my interpretion of your rules above, it'd potentially parse as a Path, and return the last segment, which means we'd be showing "www.bing.com". The only slight silver lining in that, is that we'd show the pageshot favicon, so it'd just be confusing and not a malicious attempt at clicking a link that looks like their banking site, but actually goes to "http://badsite.com/lookout/wellsfargo.com" where it steals all your banking info (which is still possible, if they've previous visited a malicious site/url and it happens to get into top sites, and they have a compelling favicon and special URL).

**Comment by nchapman** [comment]
I forgot to post this. Here's a test of the above rules on my top 100 sites:

https://gist.github.com/nchapman/36502ad115e8825d522a66549971a3f0

There are a few obvious failures. I think we could add a rule to fall back to the domain when the last section of the path contains something common and useless (`index`, `render`, etc). Obviously there will be failing no matter which approach we take. This one *seems* to hold up reasonably well.

**Comment by pdehaan** [comment]
And here's your list of URLs, but using domain-based display: https://gist.github.com/pdehaan/1b4d115ec1b943d16899d4c63f7fc21b

![](http://i.imgur.com/WTDnnwE.gif)

There are a few odd edges in [**tldjs**](http://npm.im/tldjs) I don't seem to understand. Specifically around [`#getPublicSuffix()`](https://www.npmjs.com/package/tldjs#getpublicsuffix) returning more than I expect for AWS and Heroku. Plus I may have a few more cases where we display "github" and don't even try and parse out repo names from the URL to display.

**Comment by Mardak** [comment]
For the duplication issue, currently "Top Sites" only shows the top page of a given "site" where site is a unique hostname. This means `http` and `https` of the same site will only show one item. Similarly, reddit.com/r/foo and reddit.com/r/bar will only have the most frecent one show up as one item displaying "reddit".

Duplication can appear on slightly different hostnames, e.g., "www.reddit.com" vs "reddit.com" that is easier to detect. Looking through my top 20 sites, the only potential dupes are "cloud.domain" (unnecessary subdomain) vs "domain", "www.domain" vs "m.domain" (mobile), and "www.domain" vs "wwws.domain" (secure).

**Comment by nchapman** [comment]
> Duplication can appear on slightly different hostnames, e.g., "www.reddit.com" vs "reddit.com" that is easier to detect. Looking through my top 20 sites, the only potential dupes are "cloud.domain" (unnecessary subdomain) vs "domain", "www.domain" vs "m.domain" (mobile), and "www.domain" vs "wwws.domain" (secure).

@Mardak thanks this is helpful information! It seems then that this is the issue that Chris was experiencing: https://github.com/mozilla/activity-stream/issues/1300.

**Comment by pocmo** [comment]
I wonder what was the conclusion here? On Android we use the provider name (e.g. og:site_name) or if not available we us the approach mentioned above (picking path or TLD). However this fallback often results in labels that are not really descriptive.
