### ISSUE TITLE
Shield Study Add-on Engineering 

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1438]
- implement add-on activation filter to ensure that current Activity Stream users and users who have 'non standard' `about:newtab` or `about:home` are *not* included in the study

- implement strategy for maintaining the two separate experiment variants (control and AS about:newtab pages).  This could be github branches or distinct code paths

- implement data parity for the control group about:newtab.  This involves generating AS compatible pings for the default about:newtab events

see https://bugzilla.mozilla.org/show_bug.cgi?id=1301188
see #1235 

Tasks
- [x] investigate add-on init
- [x] [check timing of preload vs render vs ping] (https://github.com/mozilla/activity-stream/issues/1514)
- [x] [investigate how to monkey patch original new tab page] (https://github.com/mozilla/activity-stream/issues/1519)
- [x] [investigate overriding existing new tab telemetry module] (https://github.com/mozilla/activity-stream/issues/1520)
- [x] [Instrument tiles page for session and search/click-related events] (https://github.com/mozilla/activity-stream/issues/1570)
- [x] [try add-on as shield experiment] (https://github.com/mozilla/activity-stream/issues/1515)
- [x] [Add a 'shield_variant' field to pings] (https://github.com/mozilla/activity-stream/issues/1516)
- [x] [extract tab tracker to add-on space from] (https://github.com/mozilla/activity-stream/issues/1482)
- [x] [give default values to TabTracker init] (https://github.com/mozilla/activity-stream/issues/1540)
- [x] [verify shield pings](https://github.com/mozilla/activity-stream/issues/1522)
- [x] [determine shield parameters, e.g., duration, population] (https://github.com/mozilla/activity-stream/issues/1523)

**Comment by Mardak** [comment]
Who should determine what pings we send for new tab tiles and what payload? Probably at least click, e.g.,

`user-action-event`
```json
{
"event":"CLICK",
"page":"NEW_TAB",
"source":"TILES",
"action_position":0,
"metadata_source":"???",
"action":"activity_stream_event",
"tab_id":"-3-2",
"client_id":"...",
"addon_version":"...",
"locale":"...",
"session_id":"..."
}
```

Perhaps also `tab-session-complete`?

**Comment by tspurway** [comment]
@Mardak for "metadata_source", which would differentiate between embedly etc, we should put "tiles" or "screen-snapshot".  I think the event ping is much more important than the session ping.  It is sufficient for the first version of this to just do the event ping

**Comment by Mardak** [comment]
Currently I have pings that look like this for a search:

```json
{
    "action": "activity_stream_event",
    "addon_version": "1.1.4",
    "client_id": "b2a413f3-529d-6042-9608-871bcf94ca01",
    "event": "SEARCH",
    "locale": "en-US",
    "page": "NEW_TAB",
    "session_id": "{47849ca8-7e4f-9445-9041-49cff1b597ca}",
    "tab_id": "-3-2"
}
```
```json
{
    "action": "activity_stream_session",
    "addon_version": "1.1.4",
    "client_id": "b2a413f3-529d-6042-9608-871bcf94ca01",
    "load_reason": "newtab",
    "locale": "en-US",
    "page": "NEW_TAB",
    "session_duration": 3794,
    "session_id": "{47849ca8-7e4f-9445-9041-49cff1b597ca}",
    "tab_id": "-3-2",
    "total_bookmarks": 0,
    "total_history_size": 0,
    "unload_reason": "search",
    "url": "about:newtab"
}
```

And this for a click:
```json
{
    "action": "activity_stream_event",
    "action_position": 1,
    "addon_version": "1.1.4",
    "client_id": "b2a413f3-529d-6042-9608-871bcf94ca01",
    "event": "CLICK",
    "locale": "en-US",
    "page": "NEW_TAB",
    "session_id": "{d07c7a13-2919-174e-ac31-2a0ea3dbc59a}",
    "source": "HISTORY",
    "tab_id": "-3-3"
}
```
```json
{
    "action": "activity_stream_session",
    "addon_version": "1.1.4",
    "client_id": "b2a413f3-529d-6042-9608-871bcf94ca01",
    "load_reason": "focus",
    "locale": "en-US",
    "page": "NEW_TAB",
    "session_duration": 1673,
    "session_id": "{d07c7a13-2919-174e-ac31-2a0ea3dbc59a}",
    "tab_id": "-3-3",
    "total_bookmarks": 0,
    "total_history_size": 0,
    "unload_reason": "click",
    "url": "about:newtab"
}
```

Where the first one is the `user-action-event` and second is `tab-session-complete`.

**Comment by Mardak** [comment]
Main thing missing from the session seems to be total_bookmarks/total_history_size which are places queries from the activity stream module. If we do send a session ping, do we need numbers for those or can I just insert 0?

**Comment by sarracini** [comment]
Closing this since all the checklist items are done!! 🎉
