### ISSUE TITLE
Implement about:home

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1974]
- [ ] set about:home to activity stream #2598
- [x] determine feature parity list (e.g.  restore session, blank override)
- [x] does it have any design differences from New Tab?
- [ ] update TelemetryFeed to have the right `page` #2510
- [ ] send perceived about:home load_trigger telemetry #2658

**Comment by Mardak** [comment]
Existing about:home features:

- [ ] "\<Brand> Start Page" title
- [ ] Firefox / Dev Edition / Nightly brand logo
- [ ] Search
- [ ] Snippet
- [ ] Launcher (Downloads, Bookmarks, History, Add-ons, Sync, Preferences)
- [ ] about Mozilla link

**Comment by Mardak** [comment]
Tracking in "about:home" of https://github.com/mozilla/activity-stream/projects/16
