### ISSUE TITLE
A11y

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1978]
https://public.etherpad-mozilla.org/p/as-a11y-l10n

- [x] get review / run through checklist #2014 
- [ ] screen readability #2015 
- [ ] modals are tab-able, closable #2024 
- [ ] contrast ratio #2028 
- [ ] button/icon labels #2030 
- [ ] text/icon sizes #2035 
- [ ] keyboard navigation / z-index order: #842 
- [x] context menu "..." to foreground #1993

**Comment by Mardak** [comment]
Tracking "Accessibility" https://github.com/mozilla/activity-stream/projects/16
