### ISSUE TITLE
L10N, I18N, RTL, Localization

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1981]
https://public.etherpad-mozilla.org/p/as-a11y-l10n

* [x] #2009 Export strings to pontoon process
* [x] #2012 import process from pontoon in build step
* [x] #2016 i10n implementation in React (convert hard coded strings)
* [x] #2019 localize numbers, dates, and times
* [x] #2020 review accessible text (hidden labels, alt text)
* [x] #2023 RTL CSS
* [x] #2027 i10n UI review: length, icons in RTL
* [x] #2031 Add locale property to state 
* [x] #2117 Set up pontoon-to-json
* [x] #2122 Add comments to strings.properties to help translators
* [x] #2128 Load language support files for different locales
* [x] #2129 Support centralized fallbacks for locales
* [x] #2136 Determine dir of html

* more notes in https://github.com/mozilla/activity-stream/issues/136

**Comment by pdehaan** [comment]
FWIW, there was an early PR #429 by @stasm which may be a good starting point for some of these.

**Comment by Mardak** [comment]
One thing we did for loop/hello was we had an en-US fallback if there were missing strings. This required some special packaging so that only 2 locales would be built for an add-on instead of all locales being available.

https://github.com/mozilla/loop/blob/master/add-on/jar.mn#L8

**Comment by k88hudson** [comment]
I talked to mathjazz about support for the ICU message format in pontoon – he's going to get back to us in the next couple of days. Otherwise, we can just use https://github.com/mozilla/pontoon-to-json/

**Comment by sarracini** [comment]
L10n is done! Closing this :)
