### ISSUE TITLE
Newtab parity (pinning, directory tiles)

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1982]
- [x] directory tiles are going away: make sure people know
- [ ] create QA checklist
- [ ] upgrade path for import old tiles customization data #2033
- [x] show blank option #2021 
- [ ] undo / unblock #2022
- [x] preload about:newtab
- [ ] customization features #1987 
- [ ] offline state #2032
- [x] chrome importing #675
- [ ] restore all blocked sites #2026
- [x] live updating of other newtab pages #2029

**Comment by sarracini** [comment]
- [] drag and drop makes a site pinned

**Comment by Mardak** [comment]
Tracking "about:newtab Parity" https://github.com/mozilla/activity-stream/projects/16
