### ISSUE TITLE
Snippets integration

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1985]
- [x] Integrate pulling payload from snippet service #2013
- [x] Implement gSnippetsMap for snippets integration #2837 
- [x] security review
- [x] close/block behavior #2017
- [x] Enable IndexedDB on about:newtab with activity-stream https://bugzilla.mozilla.org/show_bug.cgi?id=1380343
- [x] Bump version of snippets https://github.com/mozilla/activity-stream/issues/2873
- [x] Add telemetry opt-out pref to gSnippetsMap

**Comment by k88hudson** [comment]
I did a review of the existing code and external services here: https://docs.google.com/document/d/1if87hQ9_WQ_WD5aW-unocc9DsVuaT4h3HZNTAKjxVnI/edit?usp=sharing

**Comment by k88hudson** [comment]
@glogiotatidis This is the meta bug for all the snippets integration bugs in Activity Stream
