### ISSUE TITLE
Edit Top Sites

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1987]
https://trello.com/c/0cSeinDy/105-i-want-to-customize-my-top-sites-so-that-i-can-choose-the-sites-that-are-most-important-to-me

This panel allows for customization of the Top Sites section.

- [x] [Bug #2274] UI for the panel allows for pinning of Top Site cards
- [x] [Bug #2275] UI for the panel allows for drag and drop of Top Site cards
- [x] [Bug #2524] UI allows to Add a new URL (Name, URL)
- [x] [Bug #2218] UI allows for See More/Less Top Site cards.  This behaves by adding/removing one entire row of Top Site cards.  You will always have either 1 or 2 rows.
- [x] [Bug #2525] UI allows for Edit of an individual Top Site card, which enables editing of Name and URL of card
- [x] [Bug #2273] UI allows for Delete of individual Top Site card (same func as 'dismiss')
- [x]  Storing and recalling preferences pertaining to the state of this Top Site section

**Comment by bryanbell** [comment]
https://trello.com/c/0cSeinDy/105-i-want-to-customize-my-top-sites-so-that-i-can-choose-the-sites-that-are-most-important-to-me

**Comment by rlr** [comment]
TODO list done ✔️
yay!
