### ISSUE TITLE
Setting up the next Shield Study

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2231]
We would like to launch a new Shield study.  We've made the following major changes to the addon:

- Improved top sites algorithm
- Add basic customization
- Improve topsites UI (high res icons, screenshots)

We know that performance is a major confounding factor in how we measure the difference in engagement between Tiles and Activity Stream, however we are limited in how much we can improve the performance of A-S as an SDK addon, therefore rather than attempting to improve performance we are trying to measure it as accurately as we can and then control for it in our analysis.

We would like to test how these improvements change how people react to activity stream compared to tiles in a new Shield study.

First we must do the following:

- [x] Up to date screenshots of both tiles and a-s experiences
- [x] Attach telemetry to new tab prefs: https://github.com/mozilla/activity-stream/issues/2233
- [x] Improve topsites experiment: https://github.com/mozilla/activity-stream/issues/2212
- [x] Compute screenshots async: https://github.com/mozilla/activity-stream/issues/2232
- [x] Add additional topsites metrics: https://github.com/mozilla/activity-stream/issues/2210
- [x] 2 rows of topsite experiment: https://github.com/mozilla/activity-stream/issues/2300
- [x] Design a new survey with feedback from people with survey design expertise
-- A more detailed performance question?

**Comment by sarracini** [comment]
This is all done!
