### ISSUE TITLE
Port pocket code to system-addon [Meta]

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2512]
Tickets:
- [x] Implement Feeds (stories, topics) for Top Stories
- [x] Refactor to generic Top Stories logic
- [x] Implement PreferencesPane item for Top Stories #2877 
- [x] Implement "Topics" component for Top Stories (Pocket) #2876
- [x] Implement Info option for sections #2875 
- [x] Implement Card UI #2318 
- [x] Implement empty state for sections #2568
- [x] Wire up Save To Pocket context menu action

**Comment by csadilek** [comment]
When we do this we need to fix the "View More Stories" arrow to make sure it work for both RTL and LTR:

<img width="776" alt="screen shot 2017-04-28 at 12 58 06 pm" src="https://cloud.githubusercontent.com/assets/472523/25538943/bdcc1764-2c12-11e7-9332-ec8263911af4.png">

**Comment by jaredkerim** [comment]
This is blocked pending a better understanding of how we intend to host images to pocket consumers, ie do we proxy them at the CDN level or do we cache them locally on client machines?  We need a better understanding of this from pocket and BD.

**Comment by csadilek** [comment]
We also need to refactor this to a generic top stories component, independent of Pocket. This will allow configuring alternative recommendation endpoints, by supplying a topic and story endpoint, API key and logo. Details still need to be worked out.

**Comment by csadilek** [comment]
As part of this refactoring/rewrite we should also simplify CSS where possible. See: https://github.com/mozilla/activity-stream/issues/2727

**Comment by csadilek** [comment]
Depends on: https://github.com/mozilla/activity-stream/issues/2318
