### ISSUE TITLE
Bring context menu to system-addon

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2533]
doing this in 3 tickets:
- [x] bring the UI over which won't do much but it'll be accessible #2544
- [ ] wait for places change stuff to land so i can hook up the proper events #2546
- [x] test for the UI #2545
