### ISSUE TITLE
[Meta] Re-enable content process

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2777]
In addition to undoing the backout of #2756 by relanding https://bugzilla.mozilla.org/show_bug.cgi?id=1365643

- [ ] Preloaded newtab content process is an additional process https://github.com/mozilla/activity-stream/issues/2699

- [ ] Not-busy/sufficientlyLoaded oddness with preloaded remote tab https://github.com/mozilla/activity-stream/issues/2698

- [ ] WebExtension tabs API gets confused by preloaded content https://github.com/mozilla/activity-stream/issues/2696

- [ ] Reduce impact / extra memory overhead of new tab preloading https://github.com/mozilla/activity-stream/issues/2730

**Comment by Mardak** [comment]
We are not backing out with #2756.
