### ISSUE TITLE
Prerendering meta bug

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3372]
Here are the follow up bugs filed after #2813:
- [x] #3371 Support for rtl
- [x] #3370 Support real strings
- [ ] #3367 Add dynamic prerendering 
- [x] #3366 Add tests for NewTabInit.jsm
- [x] #3365 Add tests for Base.jsx
- [ ] #3373 Add tests for activity-stream.jsx
- [x] #3498 Telemetry

**Comment by Mardak** [comment]
The remaining issues have been moved to bugs:

dynamic https://bugzilla.mozilla.org/show_bug.cgi?id=1421436
tests https://bugzilla.mozilla.org/show_bug.cgi?id=1432315
