### ISSUE TITLE
Some top sites are missing favicons

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3494]
There's various possible ways for top sites to be missing favicons:
- [x] #3493 pinned sites only use favicon if already a top sites
- [x] #3541 http vs https pages with favicon
- [ ] #3664 redirected pages with no root favicon
- [ ] newly pinned site that's not in history have no favicon
- [ ] other reasons ?

---

Old description of a proposed solution that might not actually fix the issue:
Similar to how we actively fetch screenshots, we should do the same for favicons. Otherwise, favicons might be expired (?) or not exist for some reason when there could be an icon shown instead of a letter.

**Comment by AdamHillier** [comment]
This would help with #3364 - the fix for that fetches a screenshot when a top site is added manually or updated, but doesn't fetch an icon immediately (because it can't yet without force-refreshing everything)

**Comment by sarracini** [comment]
@Mardak  can you provide a little more detail here about what case we want to actively fetch favicons? is it only if we edit/add a top site?

**Comment by Mardak** [comment]
I believe this was filed for the general case of "why am I seeing a placeholder letter" as opposed to favicon missing for a new pinned icon. Although the general case might be a little bit more tricky in that we probably don't want to download a potentially favicon-less page every time we notice there's no favicon.

Also, some of this might be less important with #3218 although unclear what's the priority of each. Do we prefer a site scraped icon over trying to actively fetch over falling back to tippy top?

**Comment by sarracini** [comment]
We attempt tippy top, then fall back to site scraped icon > 96px, then site scraped icon + screenshot.

We did add some logic to go fetch the icon if we pin something in #3559, maybe that's enough for this case?

**Comment by Mardak** [comment]
The fetching of icons in #3559 for pinned is just doing the same thing as top sites now. This issue is somewhat worse than what it would be from normal usage during this transition period to rich icons as Firefox didn't know to store the rich icons before, so some sites should have shown a rich icon but couldn't.

I believe you're on the right track thinking that this is primarily an issue for adding a pinned site as it's less likely that the user hasn't been to a page than a top frecent site (most likely visited). But even then, if the user adds a pinned site, most likely the user will go to it…

Potentially there is some situation where a previously visited site somehow doesn't have favicon data, but unless we have some steps to reproduce, it seems like it'll be tricky to come up with a solution.

**Comment by Mardak** [comment]
Looks like #3664 is another case of missing favicon. Although there we should have a favicon somewhere in places -- just not for the specific url of the topsite.

**Comment by Mardak** [comment]
Morphing this into a metabug and updated original comment as the proposed solution of "actively fetching" was without really understanding the problem. Given that there have already been some fixes and other outstanding issues and unknown causes of missing favicons, it seemed better to gather these related issues to better understand what we do and don't know yet before trying a fix.

**Comment by Mardak** [comment]
Main issue left right now seems to be tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1421428
