### ISSUE TITLE
Missing, white, loading, other poor quality screenshots of some sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3509]
- [ ] #3668 various pages result in `getScreenshot error: Error: page-thumbnail:error`
- [ ] #3672 increase settle time to avoid blank screenshot
- [x] #3673 use loaded with-cookie tab browsers for screenshots
- [ ] other reasons screenshots are poor quality

With the fancy new #3507, I put in 100 for `topSitesCount` and noticed a few problems from my history:

mint and schwab screenshot an all white section (maybe still loading?):
<img width="128" alt="image" src="https://user-images.githubusercontent.com/438537/30516675-58cef4b0-9afa-11e7-8c32-9c6d4d7d3804.png">
https://mint.intuit.com/overview.event
<img width="130" alt="image" src="https://user-images.githubusercontent.com/438537/30516764-45fb22a2-9afd-11e7-821b-df75cee307df.png">
https://www.schwab.com/

macrumors, mortgagequestions, my.nintendo don't screenshot at all:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/438537/30516676-663625ce-9afa-11e7-975a-f8bdd0e9dd2b.png">
https://www.macrumors.com/
<img width="123" alt="image" src="https://user-images.githubusercontent.com/438537/30516699-490e0a9c-9afb-11e7-94bc-545bb81553b8.png">
https://www.mortgagequestions.com/
<img width="116" alt="image" src="https://user-images.githubusercontent.com/438537/30516709-94aca0da-9afb-11e7-8ca8-6fc05a03f946.png">
https://my.nintendo.com/
(Must be something with the "M"s.)

nve.ecofactor screenshots loading spinner:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/438537/30516684-c3bd0258-9afa-11e7-97fe-e8526f82fca8.png">
https://nve.ecofactor.com/

britishairways screenshots the language prompt overlay (probably can't do much here):
<img width="121" alt="image" src="https://user-images.githubusercontent.com/438537/30516687-f1fbc9e2-9afa-11e7-87ad-70ddb47c5a37.png">
https://www.britishairways.com/en-gb/executive-club/spending-avios/reward-flights

various google (mail, docs) have login (probably can't do much here):
<img width="126" alt="image" src="https://user-images.githubusercontent.com/438537/30516693-169970d8-9afb-11e7-97bb-95690f6fb10b.png">
https://mail.google.com/
https://docs.google.com/

**Comment by Mardak** [comment]
It seems like after restarting, some sites (not listed in the previous comment) that didn't get a screenshot ended up getting a screenshot. Maybe some queue got maxxed or data got lost? Or some broken state from some previous screenshot that prevented screenshotting these other sites?

**Comment by Mardak** [comment]
Let's just increase the settle time as a fix for this and ignore the other problems as as sites adopt rich icons, the problem goes away.

**Comment by Valeryan24** [comment]
Hello,

Firefox 57 will be a capital step in Mozilla history, with many significant and important changes in substance, a good reception and perception by users is absolutely necessary. And for that, esthetic, ergonomics, first impression are decisive, because many times people make huge critics on social medias just after a look, which can be viral...

This home and "New tab" page is something all users will see at first and very often, it can't be imperfect, and as it is designed now, it's sometime a bit ugly.

I understand that you certainly want to have same presentation (and perhaps code) for all plateforms (desktop, mobile...), but on a large screen, having so little thumbs is not so nice - in FF before 57 they were larger and we could put more than 2 x 6 on 2 rows- but I guess people wanting a better experience will be able to install addons like SpeedDial to customize precisely.

Problem is that, as said in this issue, lots of sites don't work with this design : either the favicon is not displayed on the bottom right, often screenshot does not show the entire page resume but only a (sometime big pixilated) icon, some site need a login and we only see the form, or just a blank square...

Tested on Ubuntu, ppa Firefox Next, version 57.0b6, see the picture for my 12 examples - I can make more tests on french pages to provide more informations.

I don't know if there is enough time to correct it for "all" pages before FF 57 release, or if design can still be changed / reverted, but imho this kind of presentation with heterogeneous thumbnails of most visited sites will provoke a feeling of unwarranted rejection among the general public, and obliterate the rest of positive new features...

![ff57](https://user-images.githubusercontent.com/1119619/31428593-8ec23f26-ae6b-11e7-8999-0ec167546073.png)

**Comment by Mardak** [comment]
There's various open [thumbnails] bugs that can be found on bugzilla:

https://bugzilla.mozilla.org/buglist.cgi?resolution=---&status_whiteboard=[thumbnails]
