### ISSUE TITLE
Tracking: improve delete for MVP

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#397]
------------------
[edit by @k88hudson]

For MVP, we have decided we will adding an MVP form of blocking (including a notification of "we're working on this) plus a drop down menu for history items.

* [x] #382 Block for top sites/spotlight
* [x] #483 Drop down menu/feedback for history items (in activity feed)
* [ ] #393/#389 Fill empty spaces after a delete
* [x] #484 Persist block list

Post MVP: #105 Expand delete functionality 

------------------
Yeah, delete is hard and confusing. Let's make sure we have a solid plan which covers all scenarios and is a consistent user experience. :heart:

**Comment by pdehaan** [comment]
@nchapman also suggested possibility of removing the delete button from "Top Sites" and "Highlights" if we don't have time to do the hiding logic in time for V1.

**Comment by jaredkerim** [comment]
This is complete.
