### ISSUE TITLE
[Tracking] Delete/Hide/Block feature MVP2

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#778]
Delete/Hide/Block MVP2 feature:
- [x] #105; Expand deletion UI/functionality

Validate these are fixed:

- [x] #750; _"Remove from History" button is not available in Activity Stream Timeline for bookmarked items_
- [x] #701; _Clicking on "X" should just dismiss site from activity stream, not give me a bunch of options_
- [x] #640; _"Delete from history" doesn't make sense for bookmarked items_
- [x] #571; _Unable to remove default sites from "Highlights" and "Top Sites" sections_

**Comment by bryanbell** [comment]
Thanks Ed.

**Comment by oyiptong** [comment]
@edmoz to revisit list

**Comment by sarracini** [comment]
Can you revisit #397 too @edmoz ?

**Comment by edmoz** [comment]
Team has discussed that all mvp2  work for this is done and any new issues should be triaged as they come.   For archive purposes, these were edge cases that are related:

- [ ] #393; Fill empty spaces after a delete
- [ ] #768; _If a specific link is bookmarked multiple times it has to removed just as many times in order to fully remove it_
- [ ] #657; _The Top Sites remove context menu can be opened while a Highlight or Recent Activity one is already opened_
- [ ] #639; _Visited default Top Sites receive remove option, but when removed they reappear_
